# Generated by Django 4.1.2 on 2022-10-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(
                fields=['last_name', 'first_name'], name='store_custo_last_na_2e448d_idx'),
        ),
    ]
